import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav, {LinkItem} from "@/components/Nav";
import React from "react";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const links: LinkItem[] = [
    {id: "getting-started", label: "Getting Started", href: "/getting-started" },
    {id: "simple-example", label: "Simple Example", href: "/simple-example" },
    {id: "configuration-options", label: "Configuration Options", href: "/configuration-options" },
    {id: "integrations", label: "Dependency Injection", href: "/integrations" },
    {id: "defaults", label: "Default users and roles", href: "/defaults" },
    {id: "creating-roles", label: "Creating Roles", href: "/creating-roles" },
    {id: "managing-permissions", label: "Managing Permissions", href: "/managing-permissions" },
    {id: "managing-user-roles", label: "Managing User Roles", href: "/managing-user-roles" },
    {id: "role-permission-checker", label: "Role & Permission Checker", href: "/role-permission-checker" },
    {id: "batteries-included", label: "Batteries Included", href: "/batteries-included" },
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.variable} antialiased`}
        >
        <div className="min-h-screen bg-zinc-50 dark:bg-black font-sans">
            <div className="flex flex-col md:flex-row">
                <Nav title="AuthTuna" links={links}/>
                <main
                    className="flex min-h-screen w-full flex-col items-center justify-start py-20 sm:items-start mx-auto md:ml-[15%]">
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
