import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Nav, {LinkItem} from "@/components/Nav";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const links: LinkItem[] = [
    {id: "intro", label: "Intro"},
    {id: "installation", label: "Installation"},
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="min-h-screen bg-zinc-50 dark:bg-black font-sans">
            <div className="flex">
                <Nav title="AuthTuna" links={links}/>

                {/* Main content */}
                <main
                    className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-start py-16 px-6 sm:items-start mx-auto">
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
