import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav, {LinkItem} from "@/components/Nav";
import React from "react";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const links: LinkItem[] = [
    {id: "intro", label: "Intro"},
    {id: "installation", label: "Installation"},
];

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.variable} antialiased`}
        >
        <div className="min-h-screen bg-zinc-50 dark:bg-black font-sans">
            <div className="flex flex-col md:flex-row">
                <Nav title="AuthTuna" links={links}/>
                <main
                    className="flex min-h-screen w-full flex-col items-center justify-start py-16 sm:items-start mx-auto">
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
