name: Publish Package on setup.py change

on:
  push:
    branches:
      - "main" # Only run on pushes to the main branch
    paths:
      - "setup.py" # Only run if setup.py is changed

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/authtuna
    permissions:
      id-token: write # This is all that's needed for authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1